### PR TITLE
Fix footer.

### PR DESCRIPTION
**Pull request by IvanSanchezSalvador**
image

### CODE REVIEW

**Comment by IvanSanchezSalvador** [comment]
Put the label HACKTOBERFEST-ACCEPTED, thanks

**Comment by Evie-Skinner18** [comment]
Hi @IvanSanchezSalvador thanks for contributing! Please can you pul the original repo's main branch into your fix_footer branch?

**Comment by IvanSanchezSalvador** [comment]
Yes of course, but please put the this label into this MR -> hacktoberfest-accepted, thanks.

**Comment by IvanSanchezSalvador** [comment]
Hi @Evie-Skinner18, the pull is applied, please can you put the label into this merge request please, the label is this hacktoberfest-accepted, thanks.

**Comment by Evie-Skinner18** [comment]
@Harriethw can you give me write access to the repo? I'm trying to merge main into this branch but merging is currently blocked for me xxx
image

**Review by Evie-Skinner18 — APPROVED** [review]

**Pull request merged**
